config/routes.rb
Rails.application.routes.draw do

  root 'forms#index'

  resources :subjects
  resources :teachers
  resources :students

  resources :forms do

    resources :submissions
  end

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'pages#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
    @submission = Submission.where(form_id: @form.id).order("student_id DESC")
    respond_to do |format|
      format.html
      format.pdf do
        pdf = FormPdf.new(@submission)
        send_data pdf.render, filename: 'Exam Schedule.pdf', type: 'application/pdf'
      end
    end
  end

  # GET /forms/new
  def new
    @form = current_user.forms.build
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = current_user.forms.build(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:title, :image)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= simple_form_for(@form) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, label: 'Name of the Exam' %>
  </div>

  <div class="form-actions">
    <%= f.input :image, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<h1>Listing Forms</h1>

<div class="row">
  <% @forms.each do |form| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag form.image.url(:medium), class: 'image'), form %>
        <p>
          <strong>Name of the Exam:</strong>
          <%= form.title %>
        </p>
        <p>
          <% if form.user == current_user %>
            <%= link_to 'Edit', edit_form_path(form) %> |
            <%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>
<% if user_signed_in? %>
  <%= link_to 'New Form', new_form_path %>
<% end %>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<h1><%= @form.title %></h1>
<p>
  <%= image_tag @form.image.url(:medium) %>
</p>

<div>
  <h3>Submissions</h3>
  <span><%= link_to 'New Submission', new_form_submission_path(@form) %></span>
  <% if user_signed_in? %>
    <span class="btn btn-default pull-right"><%= link_to 'Export pdf', form_path(@form, format: "pdf") %></span>
  <% end %>
  <br>
  <br>
  <% if @submission.blank? %>
    <h5>No submissions posted</h5>
  <% else %>
    <% if user_signed_in? %>
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Student</th>
              <th>Conflict</th>
              <th>Computer</th>
              <th>Extra time</th>
              <th>Am pm</th>
              <th>Teacher</th>
              <th>Subject</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @submission.each do |submission| %>
              <tr>
                <td><%= submission.student.name if submission.student %></td>
                <td><%= submission.conflict %></td>
                <td><%= submission.computer %></td>
                <td><%= submission.extra_time %>%</td>
                <td><%= submission.am_pm %></td>
                <td><%= submission.teacher.name if submission.teacher %></td>
                <td><%= submission.subject.name if submission.subject %></td>
                <td><%= link_to 'Edit', edit_form_submission_path(submission.form, submission) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  <% end %>
</div>
<br>
<br>
<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>